### ISSUE TITLE
Put project under some license?

### ISSUE THREAD

**Issue by MartinOSchmidt** [KiloBravoLima/PhysicalMeasure#3]
Dear KiloBravoLima,
will you put this library under some license?

Best regards

Martin

**Comment by KiloBravoLima** [comment]
Hello Martin,

I have added a license for Microsoft Public License (Ms-PL).
Hope that suits you.

Best regards
KBL

**Comment by MartinOSchmidt** [comment]
That's great, KBL.
Thanks a lot!

Martin
